### ISSUE TITLE
unable to insert |image_has_rationale=yes when {{Non-free X}} template already has parameters

### ISSUE THREAD

**Issue by voorts** [NovemLinguae/UserScripts#233]
I received the error message "ERROR: Unable to find a place to insert |image_has_rationale=yes" on [File:Harry Conover.jpg](https://en.wikipedia.org/wiki/File:Harry_Conover.jpg), which uses {{[Non-free biog-pic](https://en.wikipedia.org/wiki/Template:Non-free_biog-pic)}}.

**Comment by NovemLinguae** [comment]
I wrote a fix and tested it. Should work now.

https://test.wikipedia.org/w/index.php?title=File:Novems_test_file.png&diff=prev&oldid=622169

Thanks for reporting via GitHub. That's an easier workflow for me than on-wiki.
